### ISSUE TITLE
Can binary be an added option to the encoding mechanism

### ISSUE THREAD

**Issue by mjethanandani** [netconf-wg/https-notif#1]
Refer to the subscribed-notifications draft encoding schema for binary. Raised by Reshad.

**Comment by mjethanandani** [comment]
It is possible for this draft to enable support of binary encoding of data. The question would be how does the publisher learn if the receiver is capable of receiving binary encoding.

The receiver would have to support the OPTIONS method, and respond with ordered list with Accept-Encoding formats that it supports. The publisher at that time could then decide whether to send the notification with Content-Type as 'netconf-xml-type', 'netconf-json-type' or 'netconf-cbor-type'.

**Comment by mbj4668** [comment]
see my reply to #2.  Accept-Encoding is not the right header; this is for content-codings like deflate etc.  But also, Accept-Encoding and Accept are sent by clients, not servers, IIUC.  Hence Accept-Post.

**Comment by mjethanandani** [comment]
It appears that we cannot use OPTIONS as we do not see a way to return an ordered list of encodings. Therefore, the current proposal is to use a GET with a specific Content-Type that returns metadata, i.e. a set of encodings.

**Comment by mjethanandani** [comment]
Added in v02 of the draft.
