### ISSUE TITLE
The model needs to define a 'path' attribute.

### ISSUE THREAD

**Issue by mjethanandani** [netconf-wg/https-notif#4]
The following discussion has already happened on the mailing list.

Martin: But how is the client supposed to deliver the notifs?  PUT?  POST?  To which uri?

Kent:  ... That said, ietf-http-client fails to define a "path" field, so that appears to be
something that should be added to it.

Martin: I don't think 'path' belongs in http-client; not all http client configs require a 'path' (e.g. restconf uses it's own mechanism wih ".well-known").

Kent: True, path isn't needed for RESTCONF clients.

This draft doesn't assume anything about the server (if this is a valid assumption is discussed below) and, presumably, this assumption may be a common.  So maybe ietf-http-client should also define a feature statement for the new "path" leaf, thus servers have an easy way to turn it on.   It would be mandatory false, with the description statement indicating that it is only needed for some protocols.  Alternatively, this draft could augment in a "path" leaf into the "http-params" section, or define a new section for just the path.  Thoughts?

Martin: I prefer the latter.  I think the 'path' leaf will not be very common when the http-client grouping is used.

Kent: Sure, and by "latter", do you mean a) augment in a "path" leaf into the "http-params" section, or b) define a new section for just the path?

**Comment by mjethanandani** [comment]
Not being sure what "latter" means, I have added a "path" leaf into the "http-params" container, but outside the "http-client-grouping".

**Comment by kwatsen** [comment]
sounds right.

**Comment by mjethanandani** [comment]
Will be added to -01 version of the draft.
